global:
  # SMTP configuration for email alerts
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@your-domain.com'
  smtp_auth_username: 'alerts@your-domain.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

  # Slack webhook (optional)
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL'

# The root route for all incoming alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical alerts go to PagerDuty
    - match:
        severity: critical
      receiver: critical-receiver
      continue: true
      
    # Warning alerts go to Slack
    - match:
        severity: warning
      receiver: warning-receiver
      
    # Info alerts go to email only
    - match:
        severity: info
      receiver: info-receiver

# Inhibition rules to prevent alert spam
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'ops-team@your-domain.com'
        send_resolved: true
        headers:
          Subject: '{{ .GroupLabels.alertname }} - {{ .Status }}'
        html: |
          <h2>{{ .GroupLabels.alertname }}</h2>
          <p><b>Status:</b> {{ .Status }}</p>
          {{ range .Alerts }}
          <h3>{{ .Labels.alertname }}</h3>
          <p><b>Summary:</b> {{ .Annotations.summary }}</p>
          <p><b>Description:</b> {{ .Annotations.description }}</p>
          <p><b>Severity:</b> {{ .Labels.severity }}</p>
          <p><b>Started:</b> {{ .StartsAt }}</p>
          {{ end }}

  - name: 'critical-receiver'
    email_configs:
      - to: 'oncall@your-domain.com'
        send_resolved: true
    pagerduty_configs:
      - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
        description: '{{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#critical-alerts'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  - name: 'warning-receiver'
    slack_configs:
      - channel: '#alerts'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true
    email_configs:
      - to: 'dev-team@your-domain.com'
        send_resolved: true

  - name: 'info-receiver'
    email_configs:
      - to: 'monitoring@your-domain.com'
        send_resolved: false
        headers:
          Subject: 'INFO: {{ .GroupLabels.alertname }}'